version: '2.1'

services:
  protonmail-bridge:
    image: ghcr.io/illusorykitsune/protonmail-bridge-docker
    ports:
      - 1025:25/tcp
      - 1143:143/tcp
    restart: unless-stopped
    volumes:
      - protonmail:/root
volumes:
  protonmail:
    name: protonmail
